# Text Representation

Text representation in NLP means converting text into a numerical form that a machine learning model can understand and process.

## What is Embedding?

Embeddings in NLP is a technique where individual words are represented as real-valued vectors and captures inter-word semantics.


In this notebook, We going to intreduce 2 techniques for embedding. These techniques will be used for a machine learning models such as SVM, Random forest, ... ect.

<img src="https://drive.google.com/uc?export=view&id=1jd0u_sGppDKqBYbhtJfGxp14lnUWUTTw" width="900">

# 1- TF-IDF

<img src="https://drive.google.com/uc?export=view&id=1saSt0mMgOQ2ybbTms1lu_ruhUcBWkKzL" width="500">

TF-IDF stands for term frequency-inverse document frequency. It is a measure that discounts common words. Used in the fields of information retrieval (IR) and machine learning, that can quantify the importance of words in a document amongst a collection of documents (also known as a corpus).

### Components of TF-IDF

1. **TF (Term Frequency):**  
   Measures how frequently a term appears in a document.


$$ \text{TF}(t, d) = \frac{\text{Number of times term } t \text{ appears in document } d}{\text{Total number of terms in document } d} $$


2. **IDF (Inverse Document Frequency):**  
   Measures how important a term is across all documents. Words that appear in many documents get lower scores.

$$    \text{IDF}(t) = \log \left(\frac{\text{Number of all documents N}}{\text{Number of documents containing the term } t}\right) $$

<img src="https://drive.google.com/uc?export=view&id=1JqPILC8TTh3yDQZCSuPNXwm6ER5YeJFh" width="900">

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
doc_1 = "Data is the oil of the digital economy"
doc_2 = "Data is a new oil"

data = [doc_1, doc_2]

In [3]:
tfidf = TfidfVectorizer()
result = tfidf.fit_transform(data) # returns sparce matrix

In [6]:
import pandas as pd
df = pd.DataFrame(result.toarray(), columns=tfidf.get_feature_names_out())
df

       data  digital  economy        is       new       of       oil      the
0  0.243777  0.34262  0.34262  0.243777  0.000000  0.34262  0.243777  0.68524
1  0.448321  0.00000  0.00000  0.448321  0.630099  0.00000  0.448321  0.00000

# Cosine similarity

In NLP, Cosine similarity is a metric used to measure how similar the documents are.


$$ \text{cosine similarity} = \frac{A \cdot B}{\|A\| \times \|B\|} $$

Where:  
$ A \cdot B $  = dot product of vectors A and B  
$ \|A\| $ = magnitude (length) of vector A  
$ \|B\| $ =  magnitude (length) of vector B

#### Intuition

- If vectors point in the **same direction**, cosine similarity = **1** (maximum similarity).
- If vectors are **orthogonal (90° apart)**, cosine similarity = **0** (no similarity).

<img src="https://drive.google.com/uc?export=view&id=1b-o8CVfHBsjUGY_hXmxevU91gHidIuxO" width="900">

In [26]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
# Sample text data (replace with your own documents)

doc_1 = "Data is the oil of the digital economy"
doc_2 = "Data is a new oil"

data = [doc_1, doc_2]

In [ ]:
tfidf_vectorizer = TfidfVectorizer() # Create a CountVectorizer instance
vector_matrix = tfidf_vectorizer.fit_transform(data) # Fit and transform the documents into numerical vectors

In [ ]:
# Calculate the cosine similarity between the documents
cosine_similarity_matrix = cosine_similarity(vector_matrix)

df_cosine = pd.DataFrame(data=cosine_similarity_matrix, index=data, columns=data)

df_cosine

,Data is the oil of the digital economy,Data is a new oil
Data is the oil of the digital economy,1.000000,0.327871
Data is a new oil,0.327871,1.000000

# 2- What is Word2vec?

Word2Vec consists of models for generating word embedding. These models are two-layer neural networks having one input layer, one hidden layer, and one output layer.

Word2Vec utilizes two architectures :
1. CBOW (Continuous Bag of Words)
2. **Skip Gram**
<img src="https://drive.google.com/uc?export=view&id=1K38nEu_KhgtSJuG2RySwc6U5AAjVAgWZ" width="600">


Run this command in terminal to install
> pip install gensim

We will use fake and real news dataset to do our expirament. You can find the dataset here: https://www.kaggle.com/datasets/clmentbisaillon/fake-and-real-news-dataset?select=True.csv

In [ ]:
import pandas as pd
import nltk
import numpy as np
import gensim

from nltk.tokenize import word_tokenize

In [ ]:
df = pd.read_csv('/content/True.csv', engine='python', on_bad_lines='skip') #fake-and-real-news-dataset-true.csv
df.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [ ]:
tokens = []

for i in df['text']:
    token = word_tokenize(i)
    tokens.append(token)

In [ ]:
w2v = gensim.models.Word2Vec(tokens, min_count=1, vector_size=100, window=5, sg=1)

In [ ]:
print("Cosine similarity between 'provide' and 'program' - Skip Gram : ",w2v.wv.similarity('provide', 'program'))

Cosine similarity between 'provide' and 'program' - Skip Gram :  0.41992348

In [ ]:
print("words that similar to 'program' - Skip Gram : ",w2v.wv.most_similar('program'))

words that similar to 'program' - Skip Gram :  [('programs', 0.7426663041114807), ('programme', 0.687917172908783), ('guest-worker', 0.6685435771942139), ('EB-5', 0.66179358959198), ('seniors', 0.6605323553085327), ('arsenal', 0.659981906414032), ('expanding', 0.6542479395866394), ('abolishing', 0.6510066390037537), ('plan', 0.6469865441322327), ('marketplaces', 0.6462255120277405)]

# Tasks

### Task 1: Cosine Similarity
Use the Cosine Similarity method to determine how similar the following sentences are.

'This is the first document.',  
'This document is the second document.',  
'And this is the third one.',  
'Is this the first document?'

In [28]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [30]:
sentences = [
    "This is the first document.",
    "This document is the second document.",
    "And this is the third one.",
    "Is this the first document?"]

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(sentences)

cosine_matrix = cosine_similarity(tfidf_matrix)

df_cosine = pd.DataFrame(
    cosine_matrix,
    index=["Sentence 1", "Sentence 2", "Sentence 3", "Sentence 4"],
    columns=["Sentence 1", "Sentence 2", "Sentence 3", "Sentence 4"])

df_cosine

            Sentence 1  Sentence 2  Sentence 3  Sentence 4
Sentence 1    1.000000    0.646926    0.307772    1.000000
Sentence 2    0.646926    1.000000    0.225240    0.646926
Sentence 3    0.307772    0.225240    1.000000    0.307772
Sentence 4    1.000000    0.646926    0.307772    1.000000

### Task 2: TF-IDF
Use tf-idf method on the sentences below to determine the important words.

'data science is one of the most important fields of science',  
'this is one of the best data science courses',  
'data scientists analyze data'

In [31]:
documents = [
    "data science is one of the most important fields of science",
    "this is one of the best data science courses",
    "data scientists analyze data"
]

vectorizer = TfidfVectorizer()

tfidf_matrix = vectorizer.fit_transform(documents)

df_tfidf = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=vectorizer.get_feature_names_out(),
    index=["Document 1", "Document 2", "Document 3"]
)

df_tfidf

,analyze,best,courses,data,fields,important,is,most,of,one,science,scientists,the,this
Document 1,0.000000,0.000000,0.000000,0.189526,0.320895,0.320895,0.244049,0.320895,0.488098,0.244049,0.488098,0.000000,0.244049,0.000000
Document 2,0.000000,0.400294,0.400294,0.236420,0.000000,0.000000,0.304434,0.000000,0.304434,0.304434,0.304434,0.000000,0.304434,0.400294
Document 3,0.542701,0.000000,0.000000,0.641055,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.542701,0.000000,0.000000

In [32]:
for i, row in enumerate(tfidf_matrix.toarray()):
    scores = list(zip(vectorizer.get_feature_names_out(), row))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)

    print(f"\nDocument {i+1}:")
    for word, score in scores[:5]:
        print(word, ":", round(score, 4))

Document 1:
of : 0.4881
science : 0.4881
fields : 0.3209
important : 0.3209
most : 0.3209

Document 2:
best : 0.4003
courses : 0.4003
this : 0.4003
is : 0.3044
of : 0.3044

Document 3:
data : 0.6411
analyze : 0.5427
scientists : 0.5427
best : 0.0
courses : 0.0

## Word2vec

### Task 3:

Download the Simpsons dataset **(simpsons_script_lines.csv)** and apply the preprocessing procedure.  
Use the **'spoken_words'** column.
```
def clean_text(text):
    text = text.lower()
    text = re.sub(r"[0-9]", '', text)
    text = re.sub(r"[)(,”“.’$-]", '', text)
    return text
```
Create a skip gram Word2Vec model as below.
```
Skip_gram_model = gensim.models.Word2Vec(tokens, min_count = 1, vector_size = 100, window = 5, sg = 1)

In [33]:
from google.colab import files

uploaded = files.upload()

Saving simpsons_script_lines.csv to simpsons_script_lines (1).csv

In [34]:
import pandas as pd

df = pd.read_csv("simpsons_script_lines.csv")

In [35]:
df.columns

Index(['raw_character_text', 'spoken_words'], dtype='object')

In [36]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r"[0-9]", '', text)
    text = re.sub(r"[)(,”“.’$-]", '', text)
    return text

In [38]:
df["spoken_words"] = df["spoken_words"].fillna("")

In [39]:
df["clean_text"] = df["spoken_words"].apply(clean_text)

df[["spoken_words", "clean_text"]].head()

,spoken_words,clean_text
0,"No, actually, it was a little of both. Sometim...",no actually it was a little of both sometimes ...
1,Where's Mr. Bergstrom?,where's mr bergstrom?
2,I don't know. Although I'd sure like to talk t...,i don't know although i'd sure like to talk to...
3,That life is worth living.,that life is worth living
4,The polls will be open from now until the end ...,the polls will be open from now until the end ...

In [40]:
from nltk.tokenize import word_tokenize
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')

tokens = []

for text in df["clean_text"]:
    token = word_tokenize(text)
    tokens.append(token)

print(tokens[:5])

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

[['no', 'actually', 'it', 'was', 'a', 'little', 'of', 'both', 'sometimes', 'when', 'a', 'disease', 'is', 'in', 'all', 'the', 'magazines', 'and', 'all', 'the', 'news', 'shows', 'it', "'s", 'only', 'natural', 'that', 'you', 'think', 'you', 'have', 'it'], ['where', "'s", 'mr', 'bergstrom', '?'], ['i', 'do', "n't", 'know', 'although', 'i', "'d", 'sure', 'like', 'to', 'talk', 'to', 'him', 'he', 'did', "n't", 'touch', 'my', 'lesson', 'plan', 'what', 'did', 'he', 'teach', 'you', '?'], ['that', 'life', 'is', 'worth', 'living'], ['the', 'polls', 'will', 'be', 'open', 'from', 'now', 'until', 'the', 'end', 'of', 'recess', 'now', 'just', 'in', 'case', 'any', 'of', 'you', 'have', 'decided', 'to', 'put', 'any', 'thought', 'into', 'this', 'we', "'ll", 'have', 'our', 'final', 'statements', 'martin', '?']]

In [1]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.13/dist-packages (from gensim) (2.1.3)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.13/dist-packages (from gensim) (8.0.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.13/dist-packages (from smart_open>=1.8.1->gensim) (2.4.0)
Downloading gensim-4.4.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 63.9 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [41]:
import gensim

Skip_gram_model = gensim.models.Word2Vec(
    tokens,
    min_count=1,
    vector_size=100,
    window=5,
    sg=1
)

In [42]:
print(Skip_gram_model)

Word2Vec<vocab=44282, vector_size=100, alpha=0.025>

### Task 4

Use: wv.most_similar() method to :

1.	Find the words similar to “homer”.

2.	Find the words similar to “marge”.

3. Find the words similar to “bart”

In [43]:
Skip_gram_model.wv.most_similar("homer")

[('abe', 0.8700659275054932),
 ('marge', 0.8410359025001526),
 ('bart', 0.8130084872245789),
 ('eliza', 0.8116049766540527),
 ('mister', 0.8049063086509705),
 ('laddie', 0.8042364716529846),
 ('apu', 0.8034722805023193),
 ('bartholomew', 0.8010521531105042),
 ('ned', 0.800942599773407),
 ('jay', 0.7994297742843628)]

In [44]:
Skip_gram_model.wv.most_similar("marge")

[('abe', 0.8514006733894348),
 ('homer', 0.8410359025001526),
 ('lisa', 0.8354607820510864),
 ('sweetie', 0.8284443020820618),
 ('becky', 0.8261383771896362),
 ('eliza', 0.8129522204399109),
 ('midge', 0.8054248094558716),
 ('sweetheart', 0.8038903474807739),
 ('bea', 0.8027011156082153),
 ('allison', 0.8014172315597534)]

In [45]:
Skip_gram_model.wv.most_similar("bart")

[('lisa', 0.8749760389328003),
 ('milhouse', 0.8614053130149841),
 ('abe', 0.8553956151008606),
 ('jessica', 0.8527864217758179),
 ('laddie', 0.8437331318855286),
 ('eliza', 0.8302173614501953),
 ('stampy', 0.8284355998039246),
 ('becky', 0.8283659815788269),
 ('allison', 0.8272669911384583),
 ('grampa', 0.8261189460754395)]

### Task 5

Use the wv.doesnt_match() method to :

1.	Find which of 'jimbo', 'milhouse’, and 'kearney’ does not belong to the list.

3.	Find the odd one among "nelson", "bart", and "milhouse".

4.	Find the odd one among ‘homer', 'patty', and ‘selma'.

*Hint: You need to pass the strings as List*

In [46]:
Skip_gram_model.wv.doesnt_match(["jimbo", "milhouse", "kearney"])

'milhouse'

In [47]:
Skip_gram_model.wv.doesnt_match(["nelson", "bart", "milhouse"])

'nelson'

In [48]:
Skip_gram_model.wv.doesnt_match(["homer", "patty", "selma"])

'homer'